import 'dotenv/config';

const {
  SHOPPING_CART_STAGING_MONGOLAB_URI,
  AUTHENTICATION_SECRET,
} = process.env;

export default {
  NODE_ENV: 'staging',
  SHOPPING_CART_DB_URL: SHOPPING_CART_STAGING_MONGOLAB_URI,
  AUTHENTICATION_SECRET,
};
